### ISSUE TITLE
status 304

### ISSUE THREAD

**Issue by NelsonMinar** [tmcw/basicrequest#1]
Was reading your code because I just wrote this exact same thing; yours is half the size of mine :-) One thing you should consider is accept an HTTP 304 as the same as a 200. Some browsers seem to synthesize a 200 to the XHR even if it got a 304, but I'm not sure how consistent that is.

**Comment by tmcw** [comment]
_And three years pass_ - given the availability of `fetch`, I think it's safe to deprecate this repo :)
